export const PATTERN_LIBRARY = [
  {
    name: 'Repository',
    category: 'structural',
    tagline: 'Abstracts data access behind a collection-like interface.',
    when: 'You need to swap data sources (DB, API, mock) without changing business logic. Multiple services query the same entity.',
    whenNot: 'Simple CRUD with one data source and no complex queries. Adds a layer that buys nothing.',
    example: 'UserRepository.findByEmail() hides whether data comes from MySQL, Redis cache, or a test fixture.',
    tradeoffs: 'Testable and swappable, but adds a layer and can become a dumping ground for unrelated queries.',
    pairedWith: ['Service Layer', 'Domain Model', 'Data Mapper'],
    resources: [
      { label: 'Fowler — Repository (PoEAA)', url: 'https://martinfowler.com/eaaCatalog/repository.html' },
      { label: 'Refactoring.Guru — Repository', url: 'https://refactoring.guru/design-patterns/repository' },
      { label: 'Microsoft — Repository Pattern', url: 'https://learn.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/infrastructure-persistence-layer-design' },
    ],
  },
  {
    name: 'Data Mapper',
    category: 'structural',
    tagline: 'Maps between domain objects and database rows without coupling them.',
    when: 'Domain model and DB schema differ (e.g. snake_case DB, camelCase objects). You want domain logic free from persistence concerns.',
    whenNot: 'Schema and domain are identical — just use an ORM active record. Extra mapping is pure overhead.',
    example: 'UserMapper.toDomain(row) converts a DB row into a User domain object with business methods.',
    tradeoffs: 'Clean domain model, but more boilerplate than Active Record patterns.',
    pairedWith: ['Repository', 'Domain Model'],
    resources: [
      { label: 'Fowler — Data Mapper (PoEAA)', url: 'https://martinfowler.com/eaaCatalog/dataMapper.html' },
      { label: 'TypeORM Data Mapper docs', url: 'https://typeorm.io/active-record-data-mapper' },
    ],
  },
  {
    name: 'Domain Model',
    category: 'structural',
    tagline: 'Rich object model encapsulating both data and business behaviour.',
    when: 'Complex business rules that belong on the entity itself (e.g. Order.cancel(), Invoice.applyDiscount()).',
    whenNot: 'Simple data-in / data-out flows with no real business logic. Anemic models work fine there.',
    example: 'Order object knows how to validate its own state, calculate totals, and apply coupon rules.',
    tradeoffs: 'Business logic is co-located and testable, but requires discipline to avoid fat models.',
    pairedWith: ['Repository', 'Data Mapper', 'Service Layer'],
    resources: [
      { label: 'Fowler — Domain Model (PoEAA)', url: 'https://martinfowler.com/eaaCatalog/domainModel.html' },
      { label: 'Fowler — Anemic Domain Model (anti-pattern)', url: 'https://martinfowler.com/bliki/AnemicDomainModel.html' },
      { label: 'DDD Reference — Eric Evans', url: 'https://www.domainlanguage.com/ddd/reference/' },
    ],
  },
  {
    name: 'Facade',
    category: 'structural',
    tagline: 'Simplified interface over a complex subsystem.',
    when: 'Subsystem has many moving parts; callers only need a simple entry point. Reducing coupling to a 3rd-party library.',
    whenNot: 'Subsystem is already simple. Adding a facade just adds indirection with no benefit.',
    example: 'NotificationFacade.send(user, message) internally decides email vs push vs SMS.',
    tradeoffs: 'Hides complexity, easy to swap internals. But can become a God object if not bounded.',
    pairedWith: ['Service Layer', 'Adapter'],
    resources: [
      { label: 'Refactoring.Guru — Facade', url: 'https://refactoring.guru/design-patterns/facade' },
      { label: 'SourceMaking — Facade', url: 'https://sourcemaking.com/design_patterns/facade' },
    ],
  },
  {
    name: 'Adapter',
    category: 'structural',
    tagline: 'Converts one interface into another that a client expects.',
    when: 'Integrating a 3rd-party API or legacy system whose interface you cannot change.',
    whenNot: 'You control both sides — just align the interfaces directly.',
    example: 'StripeAdapter wraps Stripe SDK to match your internal PaymentGateway interface.',
    tradeoffs: 'Decouples you from external interfaces, but adds a translation layer to maintain.',
    pairedWith: ['Facade', 'Repository'],
    resources: [
      { label: 'Refactoring.Guru — Adapter', url: 'https://refactoring.guru/design-patterns/adapter' },
      { label: 'SourceMaking — Adapter', url: 'https://sourcemaking.com/design_patterns/adapter' },
    ],
  },
  {
    name: 'Factory',
    category: 'structural',
    tagline: 'Delegates object creation to a specialised method or class.',
    when: 'Object creation is complex, conditional, or needs to be swappable (e.g. different DB drivers per environment).',
    whenNot: 'Object creation is a single `new Foo()` — no factory needed.',
    example: 'DatabaseFactory.create(config) returns MySQLConnection or SQLiteConnection based on env.',
    tradeoffs: 'Centralises creation logic, easy to extend. Can obscure what type you actually get.',
    pairedWith: ['Adapter', 'Strategy'],
    resources: [
      { label: 'Refactoring.Guru — Factory Method', url: 'https://refactoring.guru/design-patterns/factory-method' },
      { label: 'Refactoring.Guru — Abstract Factory', url: 'https://refactoring.guru/design-patterns/abstract-factory' },
    ],
  },
  {
    name: 'Observer',
    category: 'behavioral',
    tagline: 'Notifies dependents automatically when state changes.',
    when: 'Multiple components need to react to the same event without tight coupling (e.g. user signed up → send email, update analytics, provision account).',
    whenNot: 'Only one subscriber. Direct call is clearer than an event bus.',
    example: 'UserCreated event → EmailService, AnalyticsService, and OnboardingService each listen and react.',
    tradeoffs: 'Loose coupling, easy to add subscribers. Hard to trace execution flow; ordering is implicit.',
    pairedWith: ['Pub/Sub', 'Mediator', 'Event Sourcing'],
    resources: [
      { label: 'Refactoring.Guru — Observer', url: 'https://refactoring.guru/design-patterns/observer' },
      { label: 'Fowler — Event-Driven Architecture', url: 'https://martinfowler.com/articles/201701-event-driven.html' },
    ],
  },
  {
    name: 'Strategy',
    category: 'behavioral',
    tagline: 'Selects an algorithm at runtime from a family of interchangeable ones.',
    when: 'Multiple algorithms for the same task (sorting, pricing, auth). Want to switch without conditionals.',
    whenNot: 'Only one algorithm and no foreseeable variation. Premature abstraction.',
    example: 'PaymentProcessor picks StripeStrategy or PayPalStrategy at runtime based on user preference.',
    tradeoffs: 'Open/Closed principle — easy to add strategies. Callers must know which strategy to pick.',
    pairedWith: ['Factory', 'Facade'],
    resources: [
      { label: 'Refactoring.Guru — Strategy', url: 'https://refactoring.guru/design-patterns/strategy' },
      { label: 'SourceMaking — Strategy', url: 'https://sourcemaking.com/design_patterns/strategy' },
    ],
  },
  {
    name: 'Mediator',
    category: 'behavioral',
    tagline: 'Centralises communication between components to reduce coupling.',
    when: 'Many components talk to each other and the web of dependencies is getting complex.',
    whenNot: 'Few components with simple interactions. Mediator adds ceremony for no gain.',
    example: 'CommandBus routes commands to the correct handler — controllers never import services directly.',
    tradeoffs: 'Eliminates direct coupling. Mediator can become a complex central controller.',
    pairedWith: ['CQRS', 'Observer'],
    resources: [
      { label: 'Refactoring.Guru — Mediator', url: 'https://refactoring.guru/design-patterns/mediator' },
      { label: 'MediatR library (C#/.NET)', url: 'https://github.com/jbogard/MediatR' },
    ],
  },
  {
    name: 'Pub/Sub',
    category: 'behavioral',
    tagline: 'Publishers emit events; subscribers react without direct coupling.',
    when: 'Cross-service communication, async workflows, fan-out to multiple consumers.',
    whenNot: 'You need a synchronous response from the consumer. Use direct call or request/reply instead.',
    example: 'OrderPlaced event published to a message broker → InventoryService, EmailService, FraudService each consume independently.',
    tradeoffs: 'Fully decoupled, scales well. Debugging is harder; message ordering and at-least-once delivery need handling.',
    pairedWith: ['Event Sourcing', 'Saga', 'Observer'],
    resources: [
      { label: 'Fowler — What do you mean by Event-Driven?', url: 'https://martinfowler.com/articles/201701-event-driven.html' },
      { label: 'Redis Pub/Sub docs', url: 'https://redis.io/docs/manual/pubsub/' },
      { label: 'AWS SNS/SQS — Pub/Sub pattern', url: 'https://aws.amazon.com/pub-sub-messaging/' },
    ],
  },
  {
    name: 'Webhook',
    category: 'behavioral',
    tagline: 'HTTP callback triggered by an event in an external system.',
    when: 'External system needs to push state changes to you (payment confirmed, repo push, form submitted).',
    whenNot: 'You control both sides — use direct API call or internal event instead.',
    example: 'Stripe POSTs to /webhooks/payment-confirmed when a charge succeeds.',
    tradeoffs: 'Simple integration, no polling. Must handle retries, idempotency, and signature verification.',
    pairedWith: ['Pub/Sub', 'Adapter', 'Circuit Breaker'],
    resources: [
      { label: 'Stripe Webhook docs', url: 'https://stripe.com/docs/webhooks' },
      { label: 'GitHub Webhooks docs', url: 'https://docs.github.com/en/developers/webhooks-and-events/webhooks' },
      { label: 'Webhook.site — testing tool', url: 'https://webhook.site' },
    ],
  },
  {
    name: 'CQRS',
    category: 'architectural',
    tagline: 'Separates read (Query) and write (Command) models entirely.',
    when: 'Read and write workloads have different scaling needs. Complex domain with many projections. Event Sourcing companion.',
    whenNot: 'Simple CRUD. CQRS adds two models, two stacks, and synchronisation overhead — overkill for simple apps.',
    example: 'CreateOrderCommand → write model updates DB. GetOrderSummaryQuery → read model hits a denormalised view optimised for display.',
    tradeoffs: 'Independent scaling of reads/writes, clean separation. Significant complexity; eventual consistency between models.',
    pairedWith: ['Event Sourcing', 'Mediator', 'Saga'],
    resources: [
      { label: 'Fowler — CQRS', url: 'https://martinfowler.com/bliki/CQRS.html' },
      { label: 'Microsoft — CQRS pattern', url: 'https://learn.microsoft.com/en-us/azure/architecture/patterns/cqrs' },
      { label: 'Greg Young — CQRS Documents', url: 'https://cqrs.files.wordpress.com/2010/11/cqrs_documents.pdf' },
    ],
  },
  {
    name: 'Event Sourcing',
    category: 'architectural',
    tagline: 'Stores state as an immutable log of domain events.',
    when: 'Full audit trail required. Need to replay history. Works naturally with CQRS.',
    whenNot: 'Simple state with no audit requirement. Event log grows fast and queries become complex.',
    example: 'Instead of storing current balance, store [MoneyDeposited, MoneyWithdrawn, ...] and derive balance by replaying.',
    tradeoffs: 'Perfect audit trail, time-travel debugging. Querying current state requires projection; schema evolution is hard.',
    pairedWith: ['CQRS', 'Pub/Sub', 'Saga'],
    resources: [
      { label: 'Fowler — Event Sourcing', url: 'https://martinfowler.com/eaaDev/EventSourcing.html' },
      { label: 'Microsoft — Event Sourcing pattern', url: 'https://learn.microsoft.com/en-us/azure/architecture/patterns/event-sourcing' },
      { label: 'EventStoreDB docs', url: 'https://developers.eventstore.com/' },
    ],
  },
  {
    name: 'Saga',
    category: 'architectural',
    tagline: 'Manages distributed transactions via a sequence of local transactions with compensations.',
    when: 'Multi-service transaction where you cannot use a distributed lock. Need rollback across services.',
    whenNot: 'Transaction is within a single service/DB — use a regular DB transaction.',
    example: 'BookTrip saga: reserve flight → reserve hotel → charge card. If charge fails → cancel hotel → cancel flight.',
    tradeoffs: 'Handles distributed failures gracefully. Complex to implement; compensating transactions must be idempotent.',
    pairedWith: ['CQRS', 'Event Sourcing', 'Pub/Sub'],
    resources: [
      { label: 'Microsoft — Saga distributed transactions', url: 'https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/saga/saga' },
      { label: 'Microservices.io — Saga pattern', url: 'https://microservices.io/patterns/data/saga.html' },
      { label: 'Original Saga paper (1987)', url: 'https://www.cs.cornell.edu/andru/cs711/2002fa/reading/sagas.pdf' },
    ],
  },
  {
    name: 'BFF (Backend for Frontend)',
    category: 'architectural',
    tagline: 'Dedicated backend tailored to the needs of a specific frontend.',
    when: 'Mobile and web clients need different data shapes. Aggregating multiple microservices for one screen.',
    whenNot: 'Single client or microservices already return exactly what the frontend needs.',
    example: 'Mobile BFF returns compressed, minimal payloads. Web BFF returns richer data with extra joins — same underlying services.',
    tradeoffs: 'Optimised per client, hides microservice complexity. Extra service to deploy and maintain per client type.',
    pairedWith: ['API Gateway', 'Facade', 'Service Layer'],
    resources: [
      { label: 'Fowler — BFF', url: 'https://samnewman.io/patterns/architectural/bff/' },
      { label: 'Microsoft — Backends for Frontends', url: 'https://learn.microsoft.com/en-us/azure/architecture/patterns/backends-for-frontends' },
    ],
  },
  {
    name: 'API Gateway',
    category: 'architectural',
    tagline: 'Single entry point that routes, composes, and secures API calls.',
    when: 'Multiple microservices behind a single public interface. Cross-cutting concerns: auth, rate limiting, logging.',
    whenNot: 'Monolith with a single backend — gateway is unnecessary infrastructure.',
    example: 'All requests hit api.example.com → gateway routes /users to UserService, /orders to OrderService, handles JWT validation for all.',
    tradeoffs: 'Single place for cross-cutting concerns. Single point of failure; can become a bottleneck.',
    pairedWith: ['BFF (Backend for Frontend)', 'Circuit Breaker', 'Microservice'],
    resources: [
      { label: 'Microsoft — API Gateway pattern', url: 'https://learn.microsoft.com/en-us/azure/architecture/microservices/design/gateway' },
      { label: 'Kong API Gateway', url: 'https://konghq.com/products/kong-gateway' },
      { label: 'AWS API Gateway docs', url: 'https://docs.aws.amazon.com/apigateway/latest/developerguide/welcome.html' },
    ],
  },
  {
    name: 'Microservice',
    category: 'architectural',
    tagline: 'Independently deployable service with a single bounded context.',
    when: 'Team autonomy, independent scaling, polyglot tech per domain. System is large enough to justify operational overhead.',
    whenNot: 'Small team, early-stage product. Microservices before product-market fit is premature — start with a modular monolith.',
    example: 'OrderService, InventoryService, NotificationService each deployed independently with their own DB.',
    tradeoffs: 'Independent deploy and scale. Distributed systems complexity: network failures, data consistency, observability.',
    pairedWith: ['API Gateway', 'Saga', 'Circuit Breaker', 'Pub/Sub'],
    resources: [
      { label: 'Fowler — Microservices', url: 'https://martinfowler.com/articles/microservices.html' },
      { label: 'Microservices.io patterns', url: 'https://microservices.io/patterns/index.html' },
      { label: 'Sam Newman — Building Microservices (book)', url: 'https://samnewman.io/books/building_microservices/' },
    ],
  },
  {
    name: 'Monolith Module',
    category: 'architectural',
    tagline: 'Well-bounded module within a single deployable monolith.',
    when: 'Early product, small team, or domain not yet stable. Want clear boundaries without distributed system overhead.',
    whenNot: 'Teams need independent deployments or scaling. Then extract to microservices.',
    example: 'A single Node.js app with src/modules/auth, src/modules/billing, src/modules/notifications — clear boundaries, one deploy.',
    tradeoffs: 'Simple to operate and debug. Tight coupling risk if boundaries are not enforced; scales as one unit.',
    pairedWith: ['Service Layer', 'Repository', 'Facade'],
    resources: [
      { label: 'Fowler — Modular Monolith', url: 'https://martinfowler.com/bliki/MonolithFirst.html' },
      { label: 'Shopify — Modular Rails monolith', url: 'https://engineering.shopify.com/blogs/engineering/deconstructing-monolith-designing-software-maximizes-developer-productivity' },
    ],
  },
  {
    name: 'Service Layer',
    category: 'architectural',
    tagline: 'Defines application boundary; orchestrates domain objects and infrastructure.',
    when: 'Need a clear separation between HTTP/transport layer and business logic. Multiple entry points (REST, CLI, queue) sharing the same logic.',
    whenNot: 'Trivial CRUD with no real orchestration. Service just delegates to a repository — unnecessary pass-through.',
    example: 'OrderService.placeOrder() validates input, calls OrderRepository, triggers NotificationService, logs audit — controller just calls this one method.',
    tradeoffs: 'Single place for business orchestration, easy to test. Can grow fat if not kept focused per use-case.',
    pairedWith: ['Repository', 'Domain Model', 'Facade', 'Mediator'],
    resources: [
      { label: 'Fowler — Service Layer (PoEAA)', url: 'https://martinfowler.com/eaaCatalog/serviceLayer.html' },
      { label: 'Microsoft — Application layer', url: 'https://learn.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/microservice-application-layer-implementation-web-api' },
    ],
  },
  {
    name: 'Circuit Breaker',
    category: 'architectural',
    tagline: 'Stops cascading failures by short-circuiting calls to failing services.',
    when: 'Calling external services or microservices that may be slow or down. Prevent one failure from taking down the whole system.',
    whenNot: 'Internal in-process calls. Circuit breakers are for I/O boundaries.',
    example: 'PaymentGateway circuit breaker opens after 5 failures — returns cached/fallback response instead of waiting for timeout.',
    tradeoffs: 'Resilience and fast failure. Adds state management; must tune thresholds carefully.',
    pairedWith: ['API Gateway', 'Microservice', 'Webhook', 'Saga'],
    resources: [
      { label: 'Fowler — Circuit Breaker', url: 'https://martinfowler.com/bliki/CircuitBreaker.html' },
      { label: 'Microsoft — Circuit Breaker pattern', url: 'https://learn.microsoft.com/en-us/azure/architecture/patterns/circuit-breaker' },
      { label: 'Polly (.NET resilience library)', url: 'https://github.com/App-vNext/Polly' },
    ],
  },
]

export const CATEGORIES = {
  structural:    { label: 'Structural',    color: 'bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200' },
  behavioral:    { label: 'Behavioral',    color: 'bg-purple-100 text-purple-800 dark:bg-purple-900 dark:text-purple-200' },
  architectural: { label: 'Architectural', color: 'bg-teal-100 text-teal-800 dark:bg-teal-900 dark:text-teal-200' },
}
